### ISSUE TITLE
Error running the example

### ISSUE THREAD

**Issue by matteodefelice** [FZJ-IEK3-VSA/HiSim#134]
Just installed using Anaconda. 
When I run the command `>python ../hisim/hisim_main.py examples first_example` in the folder `examples` I get this error:

```
IFO:calling first_example from examples
IFO:#################################
IFO:starting simulation of examples first_example
IFO:Start @ 13-Mar-2023 21:05:13
IFO:#################################
Traceback (most recent call last):
  File "C:\Users\matte\OneDrive\local\work\HiSim\hisim\hisim_main.py", line 76, in <module>
    main(FILE_NAME, FUNCTION_NAME)
  File "C:\Users\matte\OneDrive\local\work\HiSim\hisim\hisim_main.py", line 44, in main
    raise ValueError(f"Python script {module_filename}.py could not be found")
ValueError: Python script examples.py could not be found
```

**Comment by noah80** [comment]
Thanks for reporting that! The command line in the readme got mangled by some auto-formatter. It's fixed now and should be working again.
The correct command line is:
python ../hisim/hisim_main.py simple_examples.py first_example

**Comment by matteodefelice** [comment]
Is this a problem related to Windows:
```
FileNotFoundError: [WinError 2] "dot" not found in path.
```

**Comment by noah80** [comment]
Thanks for pointing that out. That was indeed a problem that is kind of related to Windows: We are using Graphviz, but nobody remembered to add that to the readme. Linux mostly has Graphviz installed, so noone noticed... 

I've added a section for that to the readme now and wrapped the entire thing in catch-condition that should just show an error message now to people who are missing Graphviz.

If you have time to try again, I'd be grateful for your feedback.

**Comment by matteodefelice** [comment]
Now I get a different error:
```
(hisimenv) C:\Users\matte\OneDrive\local\work\HiSim\examples> python ../hisim/hisim_main.py simple_examples.py first_example
IFO:calling first_example from simple_examples.py
IFO:#################################
IFO:starting simulation of simple_examples.py first_example
IFO:Start @ 19-Mar-2023 22:36:57
IFO:#################################
IFO:Starting first example:
IFO:Registering component outputs on Random numbers 100-200
IFO:Registering component outputs on Random numbers 10-20
IFO:Registering component outputs on Sum
IFO:Using result directory: C:\Users\matte\OneDrive\local\work\HiSim\examples\results\first_example_20230319_223657
IFO:Preparing Random numbers 100-200 for simulation.
IFO:Preparing Random numbers 10-20 for simulation.
IFO:Preparing Sum for simulation.
IFO:finished connecting all components. A total of 3 components were defined. They have a total of 3 outputs.
IFO:Starting simulation for 525600 timesteps
IFO:Simulating... 71.2% | Elapsed Time: 0:05 min | Speed: 74845 step/s | Time Left: 0:02 min| Avg. iterations 2.0
IFO:Preparing post processing
IFO:Simulation took 7.59s.
IFO:Selected 18 post processing options:
IFO:Selected post processing option: PostProcessingOptions.PLOT_LINE
IFO:Selected post processing option: PostProcessingOptions.PLOT_CARPET
IFO:Selected post processing option: PostProcessingOptions.PLOT_SANKEY
IFO:Selected post processing option: PostProcessingOptions.PLOT_SINGLE_DAYS
IFO:Selected post processing option: PostProcessingOptions.PLOT_BAR_CHARTS
IFO:Selected post processing option: PostProcessingOptions.OPEN_DIRECTORY_IN_EXPLORER
IFO:Selected post processing option: PostProcessingOptions.EXPORT_TO_CSV
IFO:Selected post processing option: PostProcessingOptions.MAKE_NETWORK_CHARTS
IFO:Selected post processing option: PostProcessingOptions.GENERATE_PDF_REPORT
IFO:Selected post processing option: PostProcessingOptions.WRITE_COMPONENTS_TO_REPORT
IFO:Selected post processing option: PostProcessingOptions.WRITE_ALL_OUTPUTS_TO_REPORT
IFO:Selected post processing option: PostProcessingOptions.WRITE_NETWORK_CHARTS_TO_REPORT
IFO:Selected post processing option: PostProcessingOptions.COMPUTE_AND_WRITE_KPIS_TO_REPORT
IFO:Selected post processing option: PostProcessingOptions.PLOT_SPECIAL_TESTING_SINGLE_DAY
IFO:Selected post processing option: PostProcessingOptions.GENERATE_CSV_FOR_HOUSING_DATA_BASE
IFO:Selected post processing option: PostProcessingOptions.INCLUDE_CONFIGS_IN_PDF_REPORT
IFO:Selected post processing option: PostProcessingOptions.INCLUDE_IMAGES_IN_PDF_REPORT
IFO:Selected post processing option: PostProcessingOptions.PROVIDE_DETAILED_ITERATION_LOGGING
IFO:Finished preparing post processing
IFO:Starting postprocessing
IFO:Main post processing function
IFO:Making line plots.
IFO:Making line plots took 49.37s.
IFO:Making carpet plots.
IFO:Making carpet plots took 3.99s.
IFO:Making single day plots.
IFO:Making single day plots took 2.12s.
IFO:Making bar charts.
IFO:Making bar plots took 1.37s.
IFO:Making sankey plots.
IFO:Plotting sankeys.
IFO:Making sankey plots took 0.00s.
IFO:Making CSV exports.
IFO:Exporting to csv.
IFO:Making CSV export took 5.05s.
IFO:Computing network charts.
ERR:Failed to generate network charts. Probably Graphviz is missing on your system. The python error was: [WinError 2] "dot" not found in path.
ERR:Failed to generate network charts. Probably Graphviz is missing on your system. The python error was: [WinError 2] "dot" not found in path.
ERR:Failed to generate network charts. Probably Graphviz is missing on your system. The python error was: [WinError 2] "dot" not found in path.
IFO:Computing network charts took 0.02s.
IFO:Making PDF report and writing simulation parameters to report.
IFO:Making PDF report and writing simulation parameters to report took 0.07s.
IFO:Writing components to report.
IFO:Writing components to report took 8.29s.
IFO:Writing all outputs to report.
IFO:Writing all outputs to report took 9.29s.
IFO:Writing network charts to report.
Traceback (most recent call last):
  File "C:\Users\matte\OneDrive\local\work\HiSim\hisim\hisim_main.py", line 76, in <module>
    main(FILE_NAME, FUNCTION_NAME)
  File "C:\Users\matte\OneDrive\local\work\HiSim\hisim\hisim_main.py", line 58, in main
    my_sim.run_all_timesteps()
  File "c:\users\matte\onedrive\local\work\hisim\hisim\simulator.py", line 259, in run_all_timesteps
    my_post_processor.run(ppdt=postprocessing_datatransfer)
  File "c:\users\matte\onedrive\local\work\hisim\hisim\utils.py", line 271, in function_wrapper_for_measuring_execution_time
    result = my_function(*args, **kwargs)
  File "c:\users\matte\onedrive\local\work\hisim\hisim\utils.py", line 296, in function_wrapper_for_measuring_memory_leak
    result = my_function(*args, **kwargs)
  File "c:\users\matte\onedrive\local\work\hisim\hisim\postprocessing\postprocessing_main.py", line 211, in run
    self.write_network_charts_to_report(ppdt, report)
  File "c:\users\matte\onedrive\local\work\hisim\hisim\postprocessing\postprocessing_main.py", line 577, in write_network_charts_to_report
    report.write_figures_to_report_with_size_four_six(
  File "c:\users\matte\onedrive\local\work\hisim\hisim\postprocessing\reportgenerator.py", line 238, in write_figures_to_report_with_size_four_six
    raise ValueError("no files found")
ValueError: no files found
```

**Comment by noah80** [comment]
Sorry about that. Didn't test properly. Now it should be fixed for real?

**Comment by matteodefelice** [comment]
solved!
