### ISSUE TITLE
ModuleNotFoundError: No module named 'obsolete'

### ISSUE THREAD

**Issue by d-esplo** [FZJ-IEK3-VSA/HiSim#354]
python ../hisim/hisim_main.py simple_system_setup_one.py
Traceback (most recent call last):
  File "C:\Users\d\anaconda3\envs\hisimvenv\HiSim\hisim\hisim_main.py", line 13, in <module>
    import hisim.simulator as sim
  File "C:\Users\d\anaconda3\envs\hisimvenv\lib\site-packages\hisim\simulator.py", line 15, in <module>
    from hisim.postprocessing import postprocessing_main as pp
  File "C:\Users\d\anaconda3\envs\hisimvenv\lib\site-packages\hisim\postprocessing\postprocessing_main.py", line 13, in <module>
    from hisim.components import building
  File "C:\Users\d\anaconda3\envs\hisimvenv\lib\site-packages\hisim\components\building.py", line 60, in <module>
    from obsolete import loadprofilegenerator_connector
ModuleNotFoundError: No module named 'obsolete'

**Comment by d-esplo** [comment]
this is only a problem when installed with pip (because older version), cloned repository shows no errors.
